# Generated by Django 5.0.4 on 2024-04-28 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
                ('currency', models.CharField(max_length=200, verbose_name='Валюта')),
                ('value', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='CurrencyChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.FloatField(blank=True, default=0, verbose_name='Относительное изменение')),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parser.countrycurrency')),
            ],
        ),
        migrations.AddField(
            model_name='countrycurrency',
            name='date',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parser.date'),
        ),
    ]
